version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    steps:
      - add_ssh_keys:
          fingerprints:
            - "72:d8:47:ce:1d:12:3d:70:25:a4:d1:4e:76:a1:9a:d4"
      - checkout
      - run:
          name: install
          command: yarn install
      - run:
          name: build
          command: yarn build
