version: 2
jobs:
  build:
    docker:
      - image: circleci/node:10
    branches:
      only:
        - master
    steps:
      - add_ssh_keys:
          fingerprints:
            - "72:d8:47:ce:1d:12:3d:70:25:a4:d1:4e:76:a1:9a:d4"
      - checkout
      - restore_cache:
          key:
            - dependencies
      - run:
          name: install
          command: yarn install
      - save_cache:
          key: dependencies
          paths:
            - node_modules
      - run:
          name: build
          command: yarn build
      - run:
          name: prepare shell commands
          # 赋予scripts权限
          command: chmod +x scripts/deploy.sh
      - run:
          name: run deploy to github pages
          # 执行shell脚本
          command: ./scripts/deploy.sh
